language: node_js
node_js:
  - "8"
env:
  - NODE_ENV=development
before_install:
  - npm i -g npm # Upgrade npm because sometimes it's outdated
install:
  - npm install
script:
  - npm run build
  - npm run lint
