version: 2
jobs:
  build:
    working_directory: /evelium
    docker:
      - image: node:8
    steps:
      - run: npm install -g npm@5 # upgrade
      - run: node --version
      - run: npm --version
      - checkout
      - run: npm install
      #- run: npm run test # TODO
      - run: npm run lint
      - run: npm run build:ci
      - store_artifacts:
          path: build
      - run:
          name: "Evelium available at url:"
          command: INSTANCE_URL="${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/build/index.html"; echo $INSTANCE_URL
